hpcaitech/ColossalAI-Examples

image/vision_transformer/data_parallel/README.md
image/vision_transformer/data_parallel/dataloader/imagenet_dali_dataloader.py

Fixed bug in dali dataloader, caused by dali update.

Fixed bug in dali dataloader, caused by dali update

---

image/simclr/README.md
image/simclr/config.py
image/simclr/le_config.py
image/simclr/train.sh
image/simclr/train_linear.py
image/simclr/train_simclr.py

SimCLR example was broken due to change of schedule, it has been fixed now.

fixed simclr example

---

language/gpt_3/dataset/webtext.py
language/gpt_3/gpt3_configs/gpt3_pp1d.py
language/gpt_3/gpt3_configs/gpt3_pp1d_min.py
language/gpt_3/gpt3_configs/gpt3_pp2d.py
language/gpt_3/gpt3_configs/gpt3_pp2p5d.py
language/gpt_3/gpt3_configs/gpt3_zero3.py
language/gpt_3/gpt3_configs/gpt3_zero3_min.py
language/gpt_3/model/__init__.py
language/gpt_3/model/embed.py
language/gpt_3/model/gpt.py
language/gpt_3/model/gpt1d.py
language/gpt_3/model/pipeline_gpt1d.py
language/gpt_3/readme.md
language/gpt_3/train_gpt.py

Migrated GPT-3 examples

---

language/gpt_2/readme.md
language/gpt_3/readme.md

corrected some language issues in both gpt-2 and gpt-3 readme files

update readme for gpt

---

features/amp/README.md
features/amp/scripts/train_slurm.sh
features/amp/train.py

- the previous amp code cannot be run
- updated the documentation

fixed broken amp example

---

image/vision_transformer/hybrid_parallel/README.md
image/vision_transformer/hybrid_parallel/configs/vit_1d_tp4_pp16.py
image/vision_transformer/hybrid_parallel/configs/vit_2d_tp4_pp16.py
image/vision_transformer/hybrid_parallel/configs/vit_2p5d_tp4_pp16.py
image/vision_transformer/hybrid_parallel/configs/vit_3d_tp8_pp8.py
image/vision_transformer/hybrid_parallel/dataloader/__init__.py
image/vision_transformer/hybrid_parallel/dataloader/dali_dataloader.py
image/vision_transformer/hybrid_parallel/model/__init__.py
image/vision_transformer/hybrid_parallel/model/vit.py
image/vision_transformer/hybrid_parallel/train_with_engine.py
image/vision_transformer/hybrid_parallel/train_with_trainer.py

- added vit hybrid paralle example
- added configs for different tensor parallelism
- added detailed readme for this example

added vit hybrid parallel example

---

features/gradient_accumulation/README.md
features/zero/README.md
features/zero/config/config_level_2.py
features/zero/config/config_level_3.py
features/zero/train_with_engine.py

Add zero example and fix some grammar errors

Add ZeRO example

---

language/gpt_2/model/__init__.py
language/gpt_3/model/__init__.py

Hi, I've fixed the bug which was because once the BERT model was in the model folder as well, and I forgot to delete it in __init__.

Fixed wrong import in __init__

---

features/pipeline_parallel/resnet.py

Current pipeline example run 60 epochs, which is too long for CI. I decrease the number of epochs.

[refactor] polish pipeline example

---

features/amp/config/config_AMP_apex.py
features/amp/config/config_AMP_naive.py
features/amp/config/config_AMP_torch.py
features/amp/config/config_fp32.py
features/amp/train_with_engine.py
features/amp/train_with_trainer.py

Reduce number of epochs to fit testing.

[refactor] polish amp example

---

image/resnet/config.py

Reduce the number of epochs to fit testing.

[refactor] polish resnet example

---

image/vision_transformer/data_parallel/config.py
image/vision_transformer/data_parallel/train.py

Reduce the number of epochs to fit testing.

[refactor] polish vit data parallel example

---

image/vision_transformer/pipeline_parallel/vit.py

Reduce the number of epochs to fit testing.

[refactor] polish vit pipeline parallel example

---

features/pipeline_parallel/resnet.py
image/vision_transformer/hybrid_parallel/train_with_engine.py
image/vision_transformer/hybrid_parallel/train_with_trainer.py
image/vision_transformer/pipeline_parallel/vit.py
language/DeepNet/train_deepnet_decoder.py
language/bert/sequene_parallel/train.py
language/gpt/train_gpt.py

The colossalAI repo has put schedule into engine module, so some old training codes need to be updated to fit refactored schedule.

change to fit refactored schedule

---

.gitignore
.pre-commit-config.yaml
.style.yapf

- Added yapf pre-commit hooks for code format consistency
- Added data to gitignore as data will the default directory where data will be downloaded

[format] added yapf pre-commit hook

---

language/bert/preprocessing/.gitignore
language/bert/preprocessing/README.md
language/bert/preprocessing/pretrain_preprocess.sh

- added bert data preprocessing scripts
- added readme for detailed instructions
- added `.gitignore` file to ignore large data files

[bert] added data preprocessing

---

language/opt/README.md

add more details about this example

update OPT README

---

image/vision_transformer/hybrid_parallel/model/vit.py
language/bert/hybrid_parallel/colossalai_utils/model_zoo/colo_bert.py
language/bert/sequene_parallel/model/bert.py
language/gpt/model/pipeline_gpt1d.py

[hotfix] fix #158 import error for partition_uniform

---

requirements.txt

Previously there are multiple requirements.txt in different dir, now I just combine them in `${ROOT}/requirements.txt`, and I retain the original requirements in each dir, maybe we could remove them later.

[requirements] modify requirements.txt

---

features/zero/train_v2.py

train_v2.py can not work under torch version 1.12.0!
@1SAA

debug zero exmaple

---

language/bert/zero/README.md
language/bert/zero/finetuning/glue/main.py
language/bert/zero/finetuning/glue/utils.py
language/bert/zero/pretraining/arguments.py
language/bert/zero/pretraining/pretrain_utils.py
language/bert/zero/pretraining/run_pretraining.py
language/bert/zero/scripts/run_finetune_glue.sh
language/bert/zero/scripts/run_pretrain.sh

Fixed the training script such that `len(dataloader)` works fine.  This script is updated with the new zero api as well.

[bert] update the zero pretraining and finetuning with new zero
